version: '3'

services:
  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'tftSQL'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'asd123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'zxcdsa1998'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - tftSQL:/var/lib/mysql
# Names our volume
volumes:
  tftSQL: